#ifndef SETUP_PREPROCESSOR_H
#define SETUP_PREPROCESSOR_H

#undef GL_COLOR_BUFFER_BIT
#undef GL_VERTEX_SHADER
#undef GL_FRAGMENT_SHADER
#undef GL_ARRAY_BUFFER
#undef GL_DYNAMIC_DRAW
#undef GL_STATIC_DRAW
#undef GL_FLOAT
#undef GL_TRIANGLES
#undef GL_TEXTURE_2D
#undef GL_TEXTURE_WRAP_S
#undef GL_TEXTURE_WRAP_T
#undef GL_CLAMP_TO_BORDER
#undef GL_TEXTURE_MIN_FILTER
#undef GL_TEXTURE_MAG_FILTER
#undef GL_LINEAR_MIPMAP_LINEAR
#undef GL_LINEAR
#undef GL_RGB
#undef GL_RGBA
#undef GL_UNSIGNED_BYTE

#endif